(export CUDA_VISIBLE_DEVICES=2 && python train_paras.py --setting 1 --quality 25 > logs/setting_1.log)&
(export CUDA_VISIBLE_DEVICES=3 && python train_paras.py --setting 2 --quality 25 > logs/setting_2.log)&
(export CUDA_VISIBLE_DEVICES=4 && python train_paras.py --setting 3 --quality 25 > logs/setting_3.log)&
(export CUDA_VISIBLE_DEVICES=5 && python train_paras.py --setting 4 --quality 25 > logs/setting_4.log)&
# (export CUDA_VISIBLE_DEVICES=5 && python train_paras.py --setting 5 --quality 25 > logs/setting_5.log)&
# (export CUDA_VISIBLE_DEVICES=4 && python train_paras.py --setting 6 --quality 25 > logs/setting_6.log)&
# (export CUDA_VISIBLE_DEVICES=5 && python train_paras.py --setting 7 --quality 25 > logs/setting_7.log)&
# (export CUDA_VISIBLE_DEVICES=6 && python train_paras.py --setting 8 --quality 25 > logs/setting_8.log)&
# (export CUDA_VISIBLE_DEVICES=7 && python train_paras.py --setting 9 --quality 25 > logs/setting_9.log)&
